"""empty message

Revision ID: 1145bb0d72d8
Revises: f3705c2b016e
Create Date: 2025-07-31 02:33:26.565721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1145bb0d72d8'
down_revision: Union[str, Sequence[str], None] = '8ba1d68693ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'source_type',
               existing_type=postgresql.ENUM('news', 'official', 'user', name='source_type'),
               nullable=False)
    op.alter_column('event', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('timeline', 'source_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('timeline', 'source_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('timeline', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('timeline', 'source_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('timeline', 'source_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('event', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'source_type',
               existing_type=postgresql.ENUM('news', 'official', 'user', name='source_type'),
               nullable=True)
    # ### end Alembic commands ###
