"""empty message

Revision ID: 2208c475f697
Revises: 1145bb0d72d8
Create Date: 2025-07-31 02:38:46.629709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2208c475f697'
down_revision: Union[str, Sequence[str], None] = '1145bb0d72d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'status',
               existing_type=postgresql.ENUM('pending', 'new', 'progress', 'done', name='event_status'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('event', 'source_type',
               existing_type=postgresql.ENUM('news', 'official', 'user', name='source_type'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'source_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('news', 'official', 'user', name='source_type'),
               existing_nullable=False)
    op.alter_column('event', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'new', 'progress', 'done', name='event_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
