"""empty message

Revision ID: 2468b3886fe1
Revises: 75b7a17f12f2
Create Date: 2025-08-02 14:43:23.248837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2468b3886fe1'
down_revision: Union[str, Sequence[str], None] = '75b7a17f12f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'like_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
