"""empty message

Revision ID: 2ef34daca3f8
Revises: f732940e4846
Create Date: 2025-07-30 17:09:05.616334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ef34daca3f8'
down_revision: Union[str, Sequence[str], None] = 'f732940e4846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('event', 'source_type',
               existing_type=postgresql.ENUM('news', 'official', 'user', name='source_type'),
               nullable=True)
    op.alter_column('event', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'source_type',
               existing_type=postgresql.ENUM('news', 'official', 'user', name='source_type'),
               nullable=False)
    op.alter_column('event', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('event', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
