"""empty message

Revision ID: 464c335a0e55
Revises: f4dd21f78eea
Create Date: 2025-07-31 01:43:22.402383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464c335a0e55'
down_revision: Union[str, Sequence[str], None] = 'f4dd21f78eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('created_by_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('timeline_created_by_fkey', 'timeline', type_='foreignkey')
    op.create_foreign_key(None, 'timeline', 'user', ['created_by_id'], ['id'])
    op.drop_column('timeline', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'timeline', type_='foreignkey')
    op.create_foreign_key('timeline_created_by_fkey', 'timeline', 'user', ['created_by'], ['id'])
    op.drop_column('timeline', 'created_by_id')
    # ### end Alembic commands ###
