"""empty message

Revision ID: 4bc265554eb6
Revises: 2468b3886fe1
Create Date: 2025-08-02 15:12:38.942692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc265554eb6'
down_revision: Union[str, Sequence[str], None] = '2468b3886fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'source_url')
    op.drop_column('event', 'source_type')
    op.drop_column('event', 'source_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
