"""empty message

Revision ID: 8ba1d68693ba
Revises: 464c335a0e55
Create Date: 2025-07-31 01:46:22.451692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba1d68693ba'
down_revision: Union[str, Sequence[str], None] = '464c335a0e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline', 'source_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('timeline', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('timeline', 'source_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
