"""empty message

Revision ID: f732940e4846
Revises: 
Create Date: 2025-07-30 17:03:20.837529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f732940e4846'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_date', sa.Date(), nullable=False))
    op.drop_column('event', 'start_date')
    op.drop_column('event', 'end_date')
    op.drop_constraint('timeline_region_id_fkey', 'timeline', type_='foreignkey')
    op.drop_column('timeline', 'region_name')
    op.drop_column('timeline', 'region_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timeline', sa.Column('region_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('timeline_region_id_fkey', 'timeline', 'region', ['region_id'], ['id'])
    op.add_column('event', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('event', 'event_date')
    # ### end Alembic commands ###
